### ISSUE TITLE
Logs are moved before sending status email - this leads to file not found error

### ISSUE THREAD

**Issue by selbitschka** [tachtler/dovecot-backup#22]
Hi,

first of all - great script - thanks for sharing this.

Using 
```
MAIL_STATUS='Y'
```
leads to 
```console
/usr/bin/cat: /tmp/dovecot_backup.log: No such file or directory
```
because of line 673.

Here you call `movelog` which remove the `FILE_LAST_LOG` before sending status email which trys to cat the `FILE_LAST_LOG`.

I just moved those line into the error if and everything works like a charn
```bash
# If errors occurred on user backups, exit with return code 1 instead of 0.
if [ "$VAR_COUNT_FAIL" -gt "0" ]; then
        sendmail ERROR
        # Move the log to the permanent log file.
        movelog
        exit 1
else
        # Status e-mail.
        if [ $MAIL_STATUS = 'Y' ]; then
                sendmail STATUS
        fi
        # Move the log to the permanent log file.
        movelog
        exit 0
fi
```
I'm not sure if you need `movelog` within the error part, but for the none error case it works.

regards
stefan

**Comment by tachtler** [comment]
Hi Stefan,

thanks for your issue report and support for dovecot_backup.sh.

I have released a new version 1.17 which corrects the bug you found and reported.

Thank you very much! 

----

Version 1.17
Bugfix - movelog does not work properly when an email is to be sent due to an error, or a status email has been requested.
Thanks to selbitschka
