### ISSUE TITLE
Suggestion: use mail_fsync=never

### ISSUE THREAD

**Issue by Alphix** [tachtler/dovecot-backup#25]
```
# rm -rf /srv/test && mkdir /srv/test && chown vmail:vmail /srv/test
# time doveadm sync -u test@example.com mdbox:/srv/test

real	213m51.795s
user	16m15.915s
sys	1m33.472s

# rm -rf /srv/test && mkdir /srv/test && chown vmail:vmail /srv/test
# time doveadm -o mail_fsync=never sync -u test@example.com mdbox:/srv/test

real	9m41.352s
user	9m0.082s
sys	0m30.458s
```

Also: creating a backup in the `mdbox` format is 15% faster in my tests than creating a backup using the `maildir` format backup, so that is also something that might make sense to change (beware of [hierarchy separator changes](https://doc.dovecot.org/configuration_manual/namespace/#hierarchy-separators) though).

**Comment by tachtler** [comment]
Hi David,

the mailbox format, has nothing to do with the backup script.

See my decision, why I'm using the MailDir format, documented in my DokuWiki.

https://dokuwiki.tachtler.net/doku.php?id=tachtler:dovecot_centos_7#vorbereitung_-_mailbox-format

Thank you,
Klaus.

**Comment by Alphix** [comment]
> Hi David,
> 
> the mailbox format, has nothing to do with the backup script.
> 
> See my decision, why I'm using the MailDir format, documented in my DokuWiki.
> 
> https://dokuwiki.tachtler.net/doku.php?id=tachtler:dovecot_centos_7#vorbereitung_-_mailbox-format
> 
> Thank you, Klaus.

Fair enough, the important part is the suggestion to use `-o mail_fsync=never` though... It will speed up the backup process no matter which format is used

**Comment by tachtler** [comment]
Hi David,

in my opinion, the backup process should be as stable as possible, and speed is not the most important thing, when using this script.

But yes you're right it's faster, but why is it faster, see the link and the answer below:

https://wiki.dovecot.org/MailLocation/LocalDisk

"By default Dovecot calls fsync() and fdatasync() whenever it's useful to prevent potential data loss. The main reason for this is so that Dovecot won't lie that the message was saved to the disk, if in fact a power failure a second later would lose the message. With IMAP clients this is perhaps a less serious problem, because the lost message was most likely either a mail in Draft mailbox or a message in "Sent Messages" mailbox. In any case a message that the user had already seen. However if [LDA](https://wiki.dovecot.org/LDA) loses a message, the user never even knew that the message existed, unless the sender decides to resend it.

Since power failures and kernel panics are quite rare, many people are tempted to disable fsyncing because it may increase the performance quite a lot. Dovecot allows this by setting mail_fsync=never. However you should consider leaving it at "optimized" for LDA and LMTP."

Greetings
Klaus.

**Comment by Alphix** [comment]
> in my opinion, the backup process should be as stable as possible, and speed is not the most important thing, when using this script.
> 
> But yes you're right it's faster, but why is it faster, see the link and the answer below:
> 
> https://wiki.dovecot.org/MailLocation/LocalDisk

With all due respect, you seem to confuse using `mail_fsync=never` for the Dovecot main process (yes, I agree that's a bad idea) with using the same option for the backup process. It's not the same thing...I fail to see how the `fsync` setting would have any relevance to the stability of the backup process....

**Comment by tachtler** [comment]
Hi David,

```doveadm sync```

calls fsync() and fdatasync() too, to prevent potential data loss. So I will not loose data while backup my mailbox.

But feel free to fork the script and implement the ```-o mail_fsync=never``` option for you.

If performance is important to you, you may need to think about a different backup strategy, such as a second Dovecot server with delayed replication.

Greetings
Klaus.
